### ISSUE TITLE
Problem following the documentation...

### ISSUE THREAD

**Issue by somoza** [mana-ethereum/ethereumex#100]
iex(9)> ABI.encode("balanceOf(address)", [address]) |> Base.encode16(case: :lower)
** (FunctionClauseError) no function clause matching in ABI.TypeEncoder.maybe_encode_unsigned/1    
    
    The following arguments were given to ABI.TypeEncoder.maybe_encode_unsigned/1:
    
        # 1
        {:ok,
         <<91, 29, 177, 3, 188, 236, 87, 218, 123, 135, 200, 13, 34, 181, 46, 75, 64,
           12, 91, 43>>}
    
    Attempted function clauses (showing 2 out of 2):
    
        defp maybe_encode_unsigned(bin) when is_binary(bin)
        defp maybe_encode_unsigned(int) when is_integer(int)
    
    (ex_abi 0.5.9) lib/abi/type_encoder.ex:272: ABI.TypeEncoder.maybe_encode_unsigned/1
    (ex_abi 0.5.9) lib/abi/type_encoder.ex:224: ABI.TypeEncoder.encode_uint/2
    (ex_abi 0.5.9) lib/abi/type_encoder.ex:100: ABI.TypeEncoder.do_encode_type/4
    (ex_abi 0.5.9) lib/abi/type_encoder.ex:83: ABI.TypeEncoder.do_encode/4
    (ex_abi 0.5.9) lib/abi/type_encoder.ex:21: ABI.TypeEncoder.encode/3

**Comment by somoza** [comment]
I found that there is a missing exclamation on the first Base.decode16.

In my case if I do this, does not work:

```
address = Application.get_env(:ethereumex, :wallet) |> String.slice(2..-1) |> Base.decode16(case: :mixed)
data = ABI.encode("balanceOf(address)", [address]) |> Base.encode16(case: :lower)
```

instead, is working this way:

```
address = Application.get_env(:ethereumex, :wallet) |> String.slice(2..-1) |> Base.decode16!(case: :mixed)
data = ABI.encode("balanceOf(address)", [address]) |> Base.encode16(case: :lower)
```

**Comment by ayrat555** [comment]
@somoza hello. thank you for looking into it! Can you please submit a pr to fix this? 🙏

**Comment by somoza** [comment]
Corse, pr created.

**Comment by ayrat555** [comment]
fixed by https://github.com/mana-ethereum/ethereumex/pull/101
