### ISSUE TITLE
Add a clear example for sending transactions.

### ISSUE THREAD

**Issue by somoza** [mana-ethereum/ethereumex#102]
```

    address           = Application.get_env(:ethereumex, :owner) |> String.slice(2..-1) |> Base.decode16!(case: :mixed)
    contract_address  = Application.get_env(:ethereumex, :contract_address)
    abi_encoded_data  = ABI.encode("setTest(uint, string)", [200, "foo"]) |> Base.encode16(case: :lower)
    
    balance_bytes = Ethereumex.HttpClient.eth_send_transaction(%{
      data: "0x" <> abi_encoded_data,
      to: contract_address,
      from: address,
      gas: "0xc350",
      gasPrice: nil
    })
```

Do I need to do a transaction first?

I got:
```** (Jason.EncodeError) invalid byte 0xFC in <<252, 83, 33, 125, 207, 109, 79, 21, 193, 116, 8, 255, 147, 246, 107, 252, 40, 46, 165, 230>>```

The README has not a clear example of sending transactions. I would be charmed to add it, but first I should know how to do that :)

**Comment by ayrat555** [comment]
can you please print and share here
```
%{
      data: "0x" <> abi_encoded_data,
      to: contract_address,
      from: address,
      gas: "0xc350",
      gasPrice: nil
    }
```

**Comment by somoza** [comment]
Hey Ayrat!

I noticed that I have to sign it with the from address' private key. I used the ETH dep for that, here is my working code:

```
abi_encoded_data  = ABI.encode("setTest(uint,string)", [1, "Foo"]) |> Base.encode16(case: :lower)
contract_address  = Application.get_env(:ethereumex, :contract_address)
account1_private_key = "5b17b72f21c486a469fb9a5f601bf53060c933a010cfc9d1900c069f536cd220"
account1_address =  Application.get_env(:ethereumex, :owner)

{:ok, tx_hash} = ETH.send_transaction(%{
  to: contract_address,
  from: account1_address,
  gas: "0xc350",
  gasPrice: nil,
  data: "0x" <> abi_encoded_data,
}, account1_private_key) #Signed as is a status modifier.
```
I can't manage this in a single way using Ethereumix...

I hope this could help somebody, even if is not the most common use to manage send transactions from the backend. I realize that people prefer to pass this task to JS on frontend in order to allow clients to use their wallets through metamask.

PS: Don't worry about the private key, it's a local Ganache environment.

**Comment by ayrat555** [comment]
@somoza hello can you please update README 🙏

**Comment by somoza** [comment]
I could and would be a pleasure indeed, but I'm not using Ethereum library but a third party. Is it not a problem to update the README?

**Comment by ayrat555** [comment]
@somoza thank you anyway!

**Comment by albertoramires** [comment]
@ayrat555 is there a way to do something similar to @somoza's example with the ethereumex library? Using a PK instead of accounts that is.
