### ISSUE TITLE
Most tests don't run on CI

### ISSUE THREAD

**Issue by rupurt** [mana-ethereum/ethereumex#107]
Most tests are currently not getting run on CI and there are several that don't run locally.

CI currently only runs `eth` & `batch`

```yaml
mix test --include eth --include batch
```

https://github.com/mana-ethereum/ethereumex/blob/master/.circleci/config.yml#L41

I've opened up a [draft PR](https://github.com/mana-ethereum/ethereumex/pull/106) to highlight the tests that are currently broken

**Comment by ayrat555** [comment]
it would be great! we also can try using another ethereum client (geth) for this

**Comment by rupurt** [comment]
@ayrat555 cool. I'm working on it now. 

My aim is to run tests/CI against multiple clients.
