### ISSUE TITLE
How do you verify a signature?

### ISSUE THREAD

**Issue by astroTANSAN** [mana-ethereum/ethereumex#118]
I see there is a sign method, but I don't see a verify method. How can I verify a signature?

**Comment by ayrat555** [comment]
@astroTANSAN Hello. I think you should use https://github.com/omgnetwork/ex_secp256k1

**Comment by astroTANSAN** [comment]
> @astroTANSAN Hello. I think you should use https://github.com/omgnetwork/ex_secp256k1
> 
> https://hexdocs.pm/ex_secp256k1/ExSecp256k1.html#verify/3

Oh, is this just basic symmetrical key sign/verify? would this mean I don't actually need the eth node to verify?

**Comment by ayrat555** [comment]
> Hello! Oh, is this just basic symmetrical key sign/verify? would this mean I don't actually need the eth node to verify?

yes
