### ISSUE TITLE
eth-call is not working on Moonbeam-Network

### ISSUE THREAD

**Issue by leeduckgo** [mana-ethereum/ethereumex#125]
```
Ethereumex.HttpClient.eth_get_transaction_by_hash("0xaee99b5c62a61b2ead425beff718fa69f7b0d44167e6c9adcf66b52cb0d60333", url: "https://rpc.api.moonbeam.network/")
```

But curl is works:
<img width="798" alt="image" src="https://user-images.githubusercontent.com/12784118/166873103-1d643ef8-5bdd-47d8-9cf8-f6f829c14a8a.png">

**Comment by ayrat555** [comment]
@leeduckgo hey.

it worked fine for me 🤔 
```elixir
iex(1)> Ethereumex.HttpClient.eth_get_transaction_by_hash("0xaee99b5c62a61b2ead425beff718fa69f7b0d44167e6c9adcf66b52cb0d60333", url: "https://rpc.api.moonbeam.network/")
{:ok,
 %{
   "accessList" => [],
   "blockHash" => "0x624408d02da980883af04216aee978d349a8368997b2c8e17b4a03fa5f70de2d",
   "blockNumber" => "0xe574d",
   "chainId" => "0x504",
   "creates" => nil,
   "from" => "0xc994b5384c0d0611de2ece7d6ff1ad16c34a812f",
   "gas" => "0x166a2",
   "gasPrice" => "0x17a1df1700",
   "hash" => "0xaee99b5c62a61b2ead425beff718fa69f7b0d44167e6c9adcf66b52cb0d60333",
   "input" => "0x42842e0e000000000000000000000000c994b5384c0d0611de2ece7d6ff1ad16c34a812f000000000000000000000000833ecd8d287c13925e38350655f8e335ef752a99000000000000000000000000000000000000000000000000000000000000022b",
   "maxFeePerGas" => "0x1c49f6df00",
   "maxPriorityFeePerGas" => "0x59682f00",
   "nonce" => "0x38",
   "publicKey" => "0x630a9f4317cf986ba8d9a193a81bbde460571b67ef7a9616b3b6e149b1ec656b17719b25763c70e722d2bda49398b8a6715945816e3f18c851b92e97968ae0a2",
   "r" => "0x7e2b9f1e94386cf9f26fafd1069e2b1626d27fb9d75dcf40cbf9a3bbe2a5ed04",
   "raw" => "0xb8d602f8d3820504388459682f00851c49f6df00830166a294b6fc950c4bc9d1e4652cbedab748e8cdcfe5655f80b86442842e0e000000000000000000000000c994b5384c0d0611de2ece7d6ff1ad16c34a812f000000000000000000000000833ecd8d287c13925e38350655f8e335ef752a99000000000000000000000000000000000000000000000000000000000000022bc001a07e2b9f1e94386cf9f26fafd1069e2b1626d27fb9d75dcf40cbf9a3bbe2a5ed04a00de16b5515b725b7fd080c904ac1012ee78f96e1d3cd2f5608e163e063771b08",
   "s" => "0xde16b5515b725b7fd080c904ac1012ee78f96e1d3cd2f5608e163e063771b08",
   "standardV" => "0x1",
   "to" => "0xb6fc950c4bc9d1e4652cbedab748e8cdcfe5655f",
   "transactionIndex" => "0x1",
   "type" => "0x2",
   "v" => "0x1",
   "value" => "0x0"
 }}
```

**Comment by leeduckgo** [comment]
> @leeduckgo hey.
> 
> it worked fine for me 🤔
> 
> ```elixir
> iex(1)> Ethereumex.HttpClient.eth_get_transaction_by_hash("0xaee99b5c62a61b2ead425beff718fa69f7b0d44167e6c9adcf66b52cb0d60333", url: "https://rpc.api.moonbeam.network/")
> {:ok,
>  %{
>    "accessList" => [],
>    "blockHash" => "0x624408d02da980883af04216aee978d349a8368997b2c8e17b4a03fa5f70de2d",
>    "blockNumber" => "0xe574d",
>    "chainId" => "0x504",
>    "creates" => nil,
>    "from" => "0xc994b5384c0d0611de2ece7d6ff1ad16c34a812f",
>    "gas" => "0x166a2",
>    "gasPrice" => "0x17a1df1700",
>    "hash" => "0xaee99b5c62a61b2ead425beff718fa69f7b0d44167e6c9adcf66b52cb0d60333",
>    "input" => "0x42842e0e000000000000000000000000c994b5384c0d0611de2ece7d6ff1ad16c34a812f000000000000000000000000833ecd8d287c13925e38350655f8e335ef752a99000000000000000000000000000000000000000000000000000000000000022b",
>    "maxFeePerGas" => "0x1c49f6df00",
>    "maxPriorityFeePerGas" => "0x59682f00",
>    "nonce" => "0x38",
>    "publicKey" => "0x630a9f4317cf986ba8d9a193a81bbde460571b67ef7a9616b3b6e149b1ec656b17719b25763c70e722d2bda49398b8a6715945816e3f18c851b92e97968ae0a2",
>    "r" => "0x7e2b9f1e94386cf9f26fafd1069e2b1626d27fb9d75dcf40cbf9a3bbe2a5ed04",
>    "raw" => "0xb8d602f8d3820504388459682f00851c49f6df00830166a294b6fc950c4bc9d1e4652cbedab748e8cdcfe5655f80b86442842e0e000000000000000000000000c994b5384c0d0611de2ece7d6ff1ad16c34a812f000000000000000000000000833ecd8d287c13925e38350655f8e335ef752a99000000000000000000000000000000000000000000000000000000000000022bc001a07e2b9f1e94386cf9f26fafd1069e2b1626d27fb9d75dcf40cbf9a3bbe2a5ed04a00de16b5515b725b7fd080c904ac1012ee78f96e1d3cd2f5608e163e063771b08",
>    "s" => "0xde16b5515b725b7fd080c904ac1012ee78f96e1d3cd2f5608e163e063771b08",
>    "standardV" => "0x1",
>    "to" => "0xb6fc950c4bc9d1e4652cbedab748e8cdcfe5655f",
>    "transactionIndex" => "0x1",
>    "type" => "0x2",
>    "v" => "0x1",
>    "value" => "0x0"
>  }}
> ```

I found ethereum_ex 0.7.0 is work but ethereum_ex 0.9.0 is not work, lol.

**Comment by ayrat555** [comment]
@leeduckgo I used the latest version. it's working for me

can you please attach the error message that you're receiving?

**Comment by leeduckgo** [comment]
> @leeduckgo I used the latest version. it's working for me
> 
> can you please attach the error message that you're receiving?

<img width="651" alt="image" src="https://user-images.githubusercontent.com/12784118/167060999-fa191097-d750-4023-acc2-9d3d8f41de19.png">
```
{:error,
 {:invalid_json,
  %Jason.DecodeError{
    data: "POST expected with JSON body",
    position: 0,
    token: nil
  }}}
```

And Our project is:

> https://github.com/WeLightProject/tai_shang_micro_faas_system

(Just down version of ethereumex yesterday.

**Comment by ayrat555** [comment]
@leeduckgo I think your configuration was missing a header

I created a pr https://github.com/WeLightProject/tai_shang_micro_faas_system/pull/29

can you please check

**Comment by leeduckgo** [comment]
> @leeduckgo I think your configuration was missing a header
> 
> I created a pr [WeLightProject/tai_shang_micro_faas_system#29](https://github.com/WeLightProject/tai_shang_micro_faas_system/pull/29)
> 
> can you please check

thx, bro!
