### ISSUE TITLE
Tests fail on latest version of Parity

### ISSUE THREAD

**Issue by hswick** [mana-ethereum/ethereumex#43]
When I was messing around with the parity versions for the CircleCI build, I noticed that there are 4 test failures.

Can reproduce this with versions of parity between 2.0.6 and 1.11

**Comment by hswick** [comment]
@ayrat555 I didn't read your [comment](https://github.com/exthereum/ethereumex/pull/40#issuecomment-427677329) well enough and missed the line about building it from source.

**Comment by ayrat555** [comment]
I hope this issue is related only to circle ci

My local setup:
```elixir
iex(1)>  Ethereumex.IpcClient.web3_client_version
{:ok,
 "Parity-Ethereum//v2.2.0-nightly-1e9aebbc8-20181002/x86_64-linux-gnu/rustc1.29.1"}
```

**Comment by hswick** [comment]
Huh, how strange. I'll try it on some of my machines and report back when I get a chance.
