### ISSUE TITLE
Figure out why request ids are being incremented by the parameter count

### ISSUE THREAD

**Issue by masonforest** [mana-ethereum/ethereumex#48]
It looks like request ids are being incremented by the number of parameters in the request. It's possible this is happening for batch requests. Should this happen for single requests as well? It's possible this is set up correctly. If so we can close this. If not we should update it to increment the request id by 1.

**Comment by ayrat555** [comment]
it was resolved by https://github.com/mana-ethereum/ethereumex/commit/9e24f3fd03a4097d5319b40b92e494273d75070f
