### ISSUE TITLE
Default block parameter for eth_estimate_gas (and some others)

### ISSUE THREAD

**Issue by kminevskiy** [mana-ethereum/ethereumex#54]
Hi,

I was trying to use the `eth_estimate_gas` function, but it looks like it has not been tested and all calls to it were failing.

Here's the error:

`{:error, %{"code" => -32602, "message" => "too many arguments, want at most 1"}}`

So after looking at the Ethereum JSON RPC specs, I figured that default block parameters can be specified only for certain [calls](https://github.com/ethereum/wiki/wiki/JSON-RPC#the-default-block-parameter). However, when scrolling through the actual examples, some of them still specify the `quantity/tag` param.

But back to the issue at hand.

I removed the default block parameter from the [spec](https://github.com/mana-ethereum/ethereumex/blob/master/lib/ethereumex/client/base_client.ex#L168), from the function [signature](https://github.com/mana-ethereum/ethereumex/blob/master/lib/ethereumex/client/base_client.ex#L169) and body params and it works as expected. Am I doing something wrong (with your initial implementation) or is it an actual bug and I should submit a PR?

Thanks!

**Comment by hswick** [comment]
It looks like in the link you posted (https://github.com/mana-ethereum/ethereumex/blob/master/lib/ethereumex/client/base_client.ex#L168) it looks like the typespec is incorrect.

You can get around this by using the generic request function:
```elixir
Ethereumex.HttpClient.request("eth_estimateGas", params, opts)
```

**Comment by ayrat555** [comment]
https://github.com/mana-ethereum/ethereumex/pull/55 merged
