### ISSUE TITLE
Interpret empty-body responses from JSON rpc as errors

### ISSUE THREAD

**Issue by pdobacz** [mana-ethereum/ethereumex#58]
`geth` returns an empty-body HTTP response, when it happens to be brought down when a request is being handled (so it seems at least). Such response is coded `200` and as such is passed onto `Jason.decode` which gives a `Jason.DecodeError` for `""`.

Firstly: maybe you are aware of why would `geth` be doing this to me or perhaps have run into the same issue? Asking in case this is purely a `geth` issue (or myself erring somewhere).

Secondly: in case geth's behavior makes at least some sense, maybe `ethereumex`'s `HttpClient` could interpret `""` response body as something that it shouldn't pass onto `Jason` for a more sensible error message?

Steps to reproduce

1/ `IO.inspect` [here](https://github.com/mana-ethereum/ethereumex/blob/master/lib/ethereumex/http_client.ex#L12)
2/ run `geth`, connect to it and run a lot of JSON rpc queries against it (I'm giving one which should actually work, when connected to Rinkeby, in the console dump below)
3/ Ctrl+C the `geth`
4/ get this (I'm pattern matching an `{:ok...` response from `HttpClient`), mind the empty body and error:

```
{:ok,
 %HTTPoison.Response{
   body: "",
   headers: [
     {"Content-Type", "application/json"},
     {"Date", "Wed, 06 Feb 2019 11:10:42 GMT"},
     {"Content-Length", "0"}
   ],
   request: %HTTPoison.Request{
     body: "{\"id\":32523,\"jsonrpc\":\"2.0\",\"method\":\"eth_getTransactionReceipt\",\"params\":[\"0x058af4226c60a5fd54158d7e36d7614d445d071ecc595206abc44b0938272491\"]}",
     headers: [{"Content-Type", "application/json"}],
     method: :post,
     options: [hackney: [pool: :default], recv_timeout: 60000],
     params: %{},
     url: "http://localhost:8546"
   },
   request_url: "http://localhost:8546",
   status_code: 200
 }}

<snip>

    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {:invalid_json, %Jason.DecodeError{data: "", position: 0, token: nil}}}

<snip>
```

I see this is slightly along the lines of https://github.com/mana-ethereum/ethereumex/pull/19, just my issue here is that `""` could perhaps be treated as a special case?

**Comment by ayrat555** [comment]
@pdobacz 
1. I did not encounter this issue
2. I think it's a good idea to interpret `""` response as an error or at least don't try to parse `""` with Jason

I'll add a fix on the weekend or I will be happy if you'll make a PR yourself

**Comment by pdobacz** [comment]
Hi, thank you, I was away a couple of days and you beat me to it :+1:
