### ISSUE TITLE
Dialyzer complains about RPC wrappers taking booleans as arguments

### ISSUE THREAD

**Issue by pdobacz** [mana-ethereum/ethereumex#60]
I'm trying to call one of such functions:

```
Ethereumex.HttpClient.eth_get_block_by_number("0x0", false)
```

(boolean at 2nd argument) and all works fine but dialyzer complains:

```
apps/omg_eth/lib/eth.ex:95: The call 'Elixir.Ethereumex.HttpClient':eth_get_block_by_number(<<_:16,_:_*8>>,'false') will never return since it differs in the 2nd argument from the success typing arguments: (binary() | [binary()] | map(),binary() | [binary()] | map())
```

looking at https://github.com/mana-ethereum/ethereumex/blob/06e340e25e0c79c89a24c9578e8d27140b7a7f1f/lib/ethereumex/client/behaviour.ex#L36 it looks like the specs have `binary()` in that spot.

The function doesn't work with "false":

```
iex(37)> Ethereumex.HttpClient.eth_get_block_by_number("0x0", "false")
{:error,
 %{
   "code" => -32602,
   "message" => "invalid argument 1: json: cannot unmarshal string into Go value of type bool"
 }}
```

I'm not entirely sure if I'm missing something or the specs should be updated for all boolean arguments like this

**Comment by InoMurko** [comment]
Sorted https://github.com/mana-ethereum/ethereumex/pull/61. 
Thanks for reporting, @pdobacz !
