### ISSUE TITLE
multiple nodes - reconnection

### ISSUE THREAD

**Issue by henry-hz** [mana-ethereum/ethereumex#71]
Many thanks for the amazing library!
I was thinkiing a way to have a really robust way to be in synch with Ethereum events, so let me hear if it makes sense:
1. create a reconnect procedure [we can get some inspiration from [this](https://github.com/jeremyong/websocket_client/blob/master/src/websocket_client.erl) ws client.
2. connect to 2 or more nodes, and subscribe to receive from them at the same time as a redundancy connection, and simple filter to ignore one of them
3. create a Live View monitoring dashboard
4. create a cache plugin, where we check if every event is concatenated, with an alarm if we lose any of them [let's say for a timeframe of 5 days]

**Comment by InoMurko** [comment]
An architecture like that (with some adjustments) would definitely work for the particular use case you're mentioning. Perhaps this does not belong directly into ethereumex (its a thing wrapper around exposed RPC and WS functionality of eth clients) but in a separate project/repo that would then use ethereumex as a dependency.

good idea anyhow! ping me on twitter (@ino_murko) if you decide to pursue this. I would contribute! 
cheers
