### ISSUE TITLE
rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (types.Transaction)(types.txdata).R

### ISSUE THREAD

**Issue by seamon** [mana-ethereum/ethereumex#72]
hi there, thanks for your good work.

when i send transaction using `Ethereumex.HttpClient.eth_send_raw_transaction(signed_transaction)`, sometime errors occur just like that:

`no match of right hand side value: {:error, %{"code" => -32000, "message" => "rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (types.Transaction)(types.txdata).R"}}`

if i change any part of transaction, `nonce`, `gas_price`, etc., errors disappear.

i searched for a long time, it looks like a problem of RLP, mentioned years before:

[https://ethereum.stackexchange.com/questions/71616/ethereum-boardcast-shows-error-non-canonical-integer-leading-zero-bytes-for](https://ethereum.stackexchange.com/questions/71616/ethereum-boardcast-shows-error-non-canonical-integer-leading-zero-bytes-for)

[https://github.com/MOACChain/moac-core/issues/24](https://github.com/MOACChain/moac-core/issues/24)

is there something we ignored unintentionally in Ethereumex or ExRLP? and is it possible to resolve it?

thanks in advance.

**Comment by InoMurko** [comment]
hey @seamon thank you for opening this issue. Can I ask you please to reopen this issue in ExRLP? https://github.com/mana-ethereum/ex_rlp

It would be very good if you included a step-by-step example where we can replicate the issue you're mentioning. Pls also include the version of ExRLP you're using.
cheers
