### ISSUE TITLE
Absolute IPC path

### ISSUE THREAD

**Issue by rupurt** [mana-ethereum/ethereumex#84]
Hi,

How do you feel about removing the [user home prefix](https://github.com/mana-ethereum/ethereumex/blob/master/lib/ethereumex/config.ex#L10) on the IPC path? With the current approach there is no way to set an absolute path. e.g. `/tmp/my.socket`

**Comment by ayrat555** [comment]
@rupurt your suggestion sounds ok to me. Will you prepare a pr?
