### ISSUE TITLE
0.8 requests failed with basic auth urls

### ISSUE THREAD

**Issue by gregors** [mana-ethereum/ethereumex#96]
I haven't had time to dig in-depth, but it looks to me like 0.8 fails with basic auth requests
such that:

```
username:password@infura.io/my_blockchain
```

to Infura, and downgrading to 0.7.1 things work just fine.

**Comment by ayrat555** [comment]
@gregors Can you please try to pass the custom basic auth header using [this pr](https://github.com/mana-ethereum/ethereumex/pull/97)?

If the pr works for you, I'll release a new version

**Comment by gregors** [comment]
Thank you @ayrat555 !!!!!!! 🥇 works great!

**Comment by ayrat555** [comment]
merged and released in 0.9.0
